### ISSUE TITLE
Sync theme design with instances of blocks

### ISSUE THREAD

**Issue by Triloworld** [WP-Performance/press-wind#16]
Using apply is only method to keep in sync blocks right now? @ipatate 
As developing on this FSE builder we find that block will lost all capabilities of updating from theme
Is there some approach that you recommend to use?

**Comment by ipatate** [comment]
hi, sorry i don't understand your question.

**Comment by Triloworld** [comment]
> hi, sorry i don't understand your question.

Updating by adding class - how Is done when client have plenty of instances of block.

**Comment by ipatate** [comment]
I use @apply instead of tailwind class directly in block/pattern to target WP classes directly. Like wp-block-group etc.
Indeed, if you use the class directly on the block, the block inside a page will not be updated. The only solution to update a block in the page is to open a page and save it.
With external classes and @apply, you just update the css and that!
